handlers:
    wildcard:
        domain: true
        path: true
registration:
    enabled: true
database:
    type: sqlite
    dsn: xsstower.db


# Database connection documentation from gorm : https://gorm.io/docs/connecting_to_the_database.html
# database:
#    type: mysql
#    dsn: "gorm:gorm@tcp(127.0.0.1:3306)/gorm?charset=utf8&parseTime=True&loc=Local"
# database:
#    type: postgres
#    dsn: "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Europe/Paris"
# database:
#    type: sqlserver
#    dsn: "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm"