// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/config": {
            "get": {
                "description": "Get Config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Config",
                "responses": {}
            },
            "put": {
                "description": "Update config Config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Config",
                "parameters": [
                    {
                        "description": "ConfigValues",
                        "name": "ConfigValues",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "description": "Get Users list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Users",
                "responses": {}
            },
            "post": {
                "description": "Create User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "UserOptions",
                        "name": "UserCreateForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UserCreateForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/users/{user_id}": {
            "put": {
                "description": "Update User information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Users",
                "parameters": [
                    {
                        "description": "UserOptions",
                        "name": "UserUpdateForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UserUpdateForm"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Users",
                "responses": {}
            }
        },
        "/fire/{fire_id}": {
            "get": {
                "description": "Get XSS Fire information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fire",
                "responses": {}
            },
            "delete": {
                "description": "Delete Fire",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fires",
                "responses": {}
            }
        },
        "/fire/{fire_id}/file/{file_id}": {
            "get": {
                "description": "Get XSS Fire File",
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fire",
                "responses": {}
            }
        },
        "/fire/{fire_id}/share": {
            "post": {
                "description": "Enable fire sharing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fires sharing",
                "responses": {}
            },
            "delete": {
                "description": "Disable fire sharing",
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fires sharing",
                "responses": {}
            }
        },
        "/fires": {
            "get": {
                "description": "Get XSS Fires",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "XSSFire"
                ],
                "summary": "Fires",
                "responses": {}
            }
        },
        "/handler/{handler_id}/members": {
            "put": {
                "description": "Update Handler Member Role",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Update Handler Member Role",
                "parameters": [
                    {
                        "description": "HandleOptions",
                        "name": "HandlerMemberEditForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HandlerMemberEditForm"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Create Handler Member",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Create Handler Member",
                "parameters": [
                    {
                        "description": "HandleOptions",
                        "name": "HandlerMemberCreateForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HandlerMemberCreateForm"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Handler Member",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Delete Handler Member",
                "parameters": [
                    {
                        "description": "HandleOptions",
                        "name": "HandlerMemberDeleteForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HandlerMemberDeleteForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/handlers": {
            "get": {
                "description": "Get Handlers list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Handlers",
                "responses": {}
            },
            "post": {
                "description": "Update Handler information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Create Handler",
                "parameters": [
                    {
                        "description": "HandleOptions",
                        "name": "HandlerCreateForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HandlerCreateForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/handlers/{handler_id}": {
            "get": {
                "description": "Get Handler information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Handlers",
                "responses": {}
            },
            "put": {
                "description": "Update Handler information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Handlers",
                "parameters": [
                    {
                        "description": "HandleOptions",
                        "name": "HandlerUpdateForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.HandlerUpdateForm"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Handler",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Handlers"
                ],
                "summary": "Handlers",
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/logout": {
            "post": {
                "description": "Logout Not working for now",
                "produces": [
                    "application/json"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/payloads": {
            "get": {
                "description": "Get formated payloads",
                "produces": [
                    "application/json"
                ],
                "summary": "Payloads",
                "responses": {}
            }
        },
        "/sharing/{fire_id}": {
            "get": {
                "description": "Get XSS Fire information",
                "produces": [
                    "application/json"
                ],
                "summary": "Public Fire",
                "responses": {}
            }
        },
        "/sharing/{fire_id}/file/{file_id}": {
            "get": {
                "description": "Get XSS Fire File",
                "summary": "Public Fire",
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Get Users list",
                "produces": [
                    "application/json"
                ],
                "summary": "Users",
                "responses": {}
            }
        }
    },
    "definitions": {
        "admin.UserCreateForm": {
            "type": "object",
            "required": [
                "email",
                "isAdmin",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "admin.UserUpdateForm": {
            "type": "object",
            "properties": {
                "isAdmin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.HandlerCreateForm": {
            "type": "object",
            "required": [
                "dom",
                "domain",
                "path",
                "screenshot"
            ],
            "properties": {
                "dom": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "screenshot": {
                    "type": "boolean"
                }
            }
        },
        "api.HandlerMemberCreateForm": {
            "type": "object",
            "required": [
                "email",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.PermisionType"
                }
            }
        },
        "api.HandlerMemberDeleteForm": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.HandlerMemberEditForm": {
            "type": "object",
            "required": [
                "role",
                "user_id"
            ],
            "properties": {
                "role": {
                    "$ref": "#/definitions/models.PermisionType"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.HandlerUpdateForm": {
            "type": "object",
            "required": [
                "Dom",
                "Screenshot"
            ],
            "properties": {
                "CollectedPages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Dom": {
                    "type": "boolean"
                },
                "Screenshot": {
                    "type": "boolean"
                }
            }
        },
        "api.LoginForm": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.PermisionType": {
            "type": "string",
            "enum": [
                "READ",
                "WRITE",
                "OWNER"
            ],
            "x-enum-varnames": [
                "READ",
                "WRITE",
                "OWNER"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
