definitions:
  admin.UserCreateForm:
    properties:
      email:
        type: string
      isAdmin:
        type: boolean
      password:
        type: string
      username:
        type: string
    required:
    - email
    - isAdmin
    - password
    - username
    type: object
  admin.UserUpdateForm:
    properties:
      isAdmin:
        type: boolean
      password:
        type: string
    type: object
  api.HandlerCreateForm:
    properties:
      dom:
        type: boolean
      domain:
        type: string
      path:
        type: string
      screenshot:
        type: boolean
    required:
    - dom
    - domain
    - path
    - screenshot
    type: object
  api.HandlerMemberCreateForm:
    properties:
      email:
        type: string
      role:
        $ref: '#/definitions/models.PermisionType'
    required:
    - email
    - role
    type: object
  api.HandlerMemberDeleteForm:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  api.HandlerMemberEditForm:
    properties:
      role:
        $ref: '#/definitions/models.PermisionType'
      user_id:
        type: integer
    required:
    - role
    - user_id
    type: object
  api.HandlerUpdateForm:
    properties:
      CollectedPages:
        items:
          type: string
        type: array
      Dom:
        type: boolean
      Screenshot:
        type: boolean
    required:
    - Dom
    - Screenshot
    type: object
  api.LoginForm:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.PermisionType:
    enum:
    - READ
    - WRITE
    - OWNER
    type: string
    x-enum-varnames:
    - READ
    - WRITE
    - OWNER
info:
  contact: {}
paths:
  /admin/config:
    get:
      description: Get Config
      produces:
      - application/json
      responses: {}
      summary: Config
      tags:
      - Administration
    put:
      description: Update config Config
      parameters:
      - description: ConfigValues
        in: body
        name: ConfigValues
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Config
      tags:
      - Administration
  /admin/users:
    get:
      description: Get Users list
      produces:
      - application/json
      responses: {}
      summary: Users
      tags:
      - Administration
    post:
      description: Create User
      parameters:
      - description: UserOptions
        in: body
        name: UserCreateForm
        required: true
        schema:
          $ref: '#/definitions/admin.UserCreateForm'
      produces:
      - application/json
      responses: {}
      summary: Create User
      tags:
      - Administration
  /admin/users/{user_id}:
    delete:
      description: Delete User
      produces:
      - application/json
      responses: {}
      summary: Users
      tags:
      - Administration
    put:
      description: Update User information
      parameters:
      - description: UserOptions
        in: body
        name: UserUpdateForm
        required: true
        schema:
          $ref: '#/definitions/admin.UserUpdateForm'
      produces:
      - application/json
      responses: {}
      summary: Users
      tags:
      - Administration
  /fire/{fire_id}:
    delete:
      description: Delete Fire
      produces:
      - application/json
      responses: {}
      summary: Fires
      tags:
      - XSSFire
    get:
      description: Get XSS Fire information
      produces:
      - application/json
      responses: {}
      summary: Fire
      tags:
      - XSSFire
  /fire/{fire_id}/file/{file_id}:
    get:
      description: Get XSS Fire File
      responses: {}
      summary: Fire
      tags:
      - XSSFire
  /fire/{fire_id}/share:
    delete:
      description: Disable fire sharing
      responses: {}
      summary: Fires sharing
      tags:
      - XSSFire
    post:
      description: Enable fire sharing
      produces:
      - application/json
      responses: {}
      summary: Fires sharing
      tags:
      - XSSFire
  /fires:
    get:
      description: Get XSS Fires
      produces:
      - application/json
      responses: {}
      summary: Fires
      tags:
      - XSSFire
  /handler/{handler_id}/members:
    delete:
      description: Delete Handler Member
      parameters:
      - description: HandleOptions
        in: body
        name: HandlerMemberDeleteForm
        required: true
        schema:
          $ref: '#/definitions/api.HandlerMemberDeleteForm'
      produces:
      - application/json
      responses: {}
      summary: Delete Handler Member
      tags:
      - Handlers
    post:
      description: Create Handler Member
      parameters:
      - description: HandleOptions
        in: body
        name: HandlerMemberCreateForm
        required: true
        schema:
          $ref: '#/definitions/api.HandlerMemberCreateForm'
      produces:
      - application/json
      responses: {}
      summary: Create Handler Member
      tags:
      - Handlers
    put:
      description: Update Handler Member Role
      parameters:
      - description: HandleOptions
        in: body
        name: HandlerMemberEditForm
        required: true
        schema:
          $ref: '#/definitions/api.HandlerMemberEditForm'
      produces:
      - application/json
      responses: {}
      summary: Update Handler Member Role
      tags:
      - Handlers
  /handlers:
    get:
      description: Get Handlers list
      produces:
      - application/json
      responses: {}
      summary: Handlers
      tags:
      - Handlers
    post:
      description: Update Handler information
      parameters:
      - description: HandleOptions
        in: body
        name: HandlerCreateForm
        required: true
        schema:
          $ref: '#/definitions/api.HandlerCreateForm'
      produces:
      - application/json
      responses: {}
      summary: Create Handler
      tags:
      - Handlers
  /handlers/{handler_id}:
    delete:
      description: Delete Handler
      produces:
      - application/json
      responses: {}
      summary: Handlers
      tags:
      - Handlers
    get:
      description: Get Handler information
      produces:
      - application/json
      responses: {}
      summary: Handlers
      tags:
      - Handlers
    put:
      description: Update Handler information
      parameters:
      - description: HandleOptions
        in: body
        name: HandlerUpdateForm
        required: true
        schema:
          $ref: '#/definitions/api.HandlerUpdateForm'
      produces:
      - application/json
      responses: {}
      summary: Handlers
      tags:
      - Handlers
  /login:
    post:
      description: Login
      parameters:
      - description: Credentials
        in: body
        name: LoginForm
        required: true
        schema:
          $ref: '#/definitions/api.LoginForm'
      produces:
      - application/json
      responses: {}
      summary: Login
      tags:
      - Authentication
  /logout:
    post:
      description: Logout Not working for now
      produces:
      - application/json
      responses: {}
      summary: Logout
  /payloads:
    get:
      description: Get formated payloads
      produces:
      - application/json
      responses: {}
      summary: Payloads
  /sharing/{fire_id}:
    get:
      description: Get XSS Fire information
      produces:
      - application/json
      responses: {}
      summary: Public Fire
  /sharing/{fire_id}/file/{file_id}:
    get:
      description: Get XSS Fire File
      responses: {}
      summary: Public Fire
  /users:
    get:
      description: Get Users list
      produces:
      - application/json
      responses: {}
      summary: Users
swagger: "2.0"
