name: Deploy Images to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/thomasfady/xsstower:latest
              docker build . --tag ghcr.io/thomasfady/xsstower:$GITHUB_REF_NAME
              docker push ghcr.io/thomasfady/xsstower:latest
              docker push ghcr.io/thomasfady/xsstower:$GITHUB_REF_NAME
